---
  output: html_document
---
  
#### Jongchul Seon
  
#### -------- get Files from http://www.ncbi.nlm.nih.gov/gds/?term=GSE68777 ---------------------
#### please check below
#### http://kasperdanielhansen.github.io/genbioconductor/html/minfi.html
#### http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0132001 or http://www.ncbi.nlm.nih.gov/pubmed/26147665



```{r chunk1,echo=TRUE}

library(GEOquery)
library(minfi)
##library(minfiData)
library(AnnotationHub)


## source("http://www.bioconductor.org/biocLite.R")
## biocLite(c("minfi"))

getwd()

getGEOSuppFiles("GSE68777")
untar("GSE68777/GSE68777_RAW.tar", exdir = "GSE68777/idat")
head(list.files("GSE68777/idat", pattern = "idat"))

idatFiles <- list.files("GSE68777/idat", pattern = "idat.gz$", full = TRUE)

sapply(idatFiles, gunzip, overwrite = TRUE)

rgSet <- read.450k.exp("GSE68777/idat")
rgSet



##class(rgSet)
##??RGChannelSet
##??minfi

## library(illuminaio)
## library(IlluminaDataTestFiles)

## head(list.files("GSE68777/idat", pattern = "idat"))

## green1 <- readIDAT("D:/R/GSE68777/idat/GSM1681154_5958091019_R03C02_Grn.idat")

## red1 <- readIDAT("D:/R/GSE68777/idat/GSM1681154_5958091019_R03C02_Red.idat")

## names(green1)
## head(green1$Quants)

##summary(green1$Quants[,3])
##summary(red1$Quants[,1])
##hist(log2(green1$Quants[,1]))
##hist(log2(red1$Quants[,1]))


pData(rgSet)

tempdir()


```


#### -------- get the phenotype data ---------------------


```{r chunk2,echo=TRUE}

###getGEO
###geoMat <- getGEO("GSE68777")
geoMat <- getGEO("GSE68777",destdir = "D:\\R")

### destdir = "D:\\R" => window OS directory


pD.all <- pData(geoMat[[1]])

class(pD.all)
head(pD.all)
names(pD.all)

```

#### -------- modify phenotype data for further analysis-----------------------------------------

```{r chunk3,echo=TRUE}


pD <- pD.all[, c("title", "geo_accession", "characteristics_ch1.1", "characteristics_ch1.2")]
head(pD)

names(pD)[c(3,4)] <- c("group", "sex")
head(pD)

pD$group
pD$group <- sub("^diagnosis: ", "", pD$group)
pD$group

pD$sex 
pD$sex <- sub("^Sex: ", "", pD$sex)
pD$sex

sampleNames(rgSet) 
sampleNames(rgSet) <- sub(".*_5", "5", sampleNames(rgSet))
sampleNames(rgSet) 

rownames(pD) <- pD$title
pD <- pD[sampleNames(rgSet),]
pData(rgSet) <- pD
pData(rgSet)
rgSet



```


#### -------- data Normalization 
####---------- Please check the paper, Functional normalization of 450k methylation array data improves replication in large cancer studies,http://www.genomebiology.com/2014/15/12/503
-----------------------------------------

```{r chunk4,echo=TRUE}

preprocessFunnorm



grSet2 <- preprocessFunnorm(rgSet)

grSet2$group


```


#### --------please check http://genomicsclass.github.io/book/pages/inference_for_DNAmeth.html

```{r chunk5,echo=TRUE}

## design <- model.matrix(~ grSet2$group)
## bumps <- bumphunter(grSet2, design = design, B = 0,
                      type = "Beta", cutoff = 0.25)

## class(bumps)
## attributes(bumps)

## head(bumps$table)
## plot((bumps$table)[,4])
## dim(bumps$table)

control <- getBeta(grSet2[,grSet2$group == "Ctr"])

mania <- getBeta(grSet2[,grSet2$group == "Mania"])


total <- cbind(rowSums(control),rowSums(mania))
plot(total,col=3)


head(control)
hist(control[1,])
hist(control[3,])
hist(rowSums(control))


kmeans1 = kmeans(rowSums(control),centers=2)
table(kmeans1$cluster)


kmeans2 = kmeans(rowSums(mania),centers=2)
table(kmeans2$cluster)


rownames(control)

cg_status <- getIslandStatus(grSet2)

control_cg <- cbind(control,cg_status)

mania_cg <- cbind(mania,cg_status)

control_os <- subset(control_cg,cg_status == "OpenSea")
mania_os <- subset(mania_cg,cg_status == "OpenSea")

mean(as.numeric(control_os[,1:20]))
mean(as.numeric(mania_os[,1:20]))


```

