---
  output: html_document
---
  
#### Jongchul Seon

#### data loading  
#### please check below
#### http://www.ncbi.nlm.nih.gov/pubmed/26343147

```{r chunk1,echo=TRUE}

library(GEOquery)
library(oligo)
library(dendextend)
library(biomaRt)

getwd()

getGEOSuppFiles("GSE59880")
list.files("GSE59880")
untar("GSE59880/GSE59880_RAW.tar", exdir = "GSE59880/CEL")
list.files("GSE59880/CEL")

celfiles <- list.files("GSE59880/CEL", full = TRUE)
rawData <- read.celfiles(celfiles)


###library(pd.hg.u133.plus.2)

```


#### dara normalization
#### please check https://github.com/kasperdanielhansen/genbioconductor/blob/master/Rmd/oligo.Rmd

```{r chunk2,echo=TRUE}

dim(exprs(rawData))

exprs(rawData)[1:10,]

sum(is.na(exprs(rawData)))

hist(exprs(rawData)[,1])

boxplot(log(exprs(rawData))[,1:5],col=2)


##dist1 = dist(t(exprs(rawData)))
##hclust1 = hclust(dist1)
##plot(hclust1)

##dend = as.dendrogram(hclust1)
##dend = color_labels(hclust1,2,col=1:2)
##plot(dend)


normData <- rma(rawData)
normData

dim(normData)

boxplot(normData,col=2)


```


####select gene expression data strongly related with aging according to the paper. 
 

```{r chunk3,echo=TRUE}

library(xlsx)
data <- read.xlsx("13059_2015_750_MOESM1_ESM.xlsx", 1, startRow=2, endRow=152,colIndex=1)

head(data)

genes <- as.vector(as.matrix(data))

genes_age <- exprs(normData)[rownames(exprs(normData))  %in% genes,]


```


#### The phenotype data loading 


```{r chunk4,echo=TRUE}

geoMat <- getGEO("GSE59880",destdir = "D:\\R")

### destdir = "D:\\R" => window OS directory


pD.all <- pData(geoMat[[1]])

class(pD.all)
head(pD.all)
names(pD.all)

pD <- pD.all[, c("title", "geo_accession", "characteristics_ch1.1","characteristics_ch1.2","characteristics_ch1.3","characteristics_ch1.4","platform_id"  )]


pD <- pD.all[, c("title", "geo_accession", "characteristics_ch1.1","characteristics_ch1.2")]

head(pD)

names(pD)[c(3,4)] <- c("age", "fitness")
head(pD)


pD$age
pD$age <- sub("^age: ","", pD$age)
pD$age

pD$fitness 
pD$fitness <- sub("^aerobic fitness: ", "", pD$fitness)
pD$fitness

normData
??ExpressionSet

sampleNames(normData) <- sub("^_*.CEL.gz$", "", sampleNames(normData))
sampleNames(normData)

changeName <- function(x) {
  
    print("function starts.... object length is")
    print(length(x))
    
    for (i in 1:length(x)) {
    
      x[i] <- substr(x[i], start=1, stop=10) 
      
      print(x[i])
    }
     
  return(x)
   
}

sampleNames(normData) <- changeName(sampleNames(normData))

sampleNames(normData)

rownames(pD) 

```


```{r chunk4,echo=TRUE}

head(listMarts())
mart <- useMart("ensembl")
mart
head(listDatasets(mart))
ensembl <- useDataset("hsapiens_gene_ensembl", mart)
ensembl

values <- genes
getBM(attributes = c("ensembl_gene_id", "affy_hg_u133_plus_2"),
      filters = "affy_hg_u133_plus_2", values = values, mart = ensembl)

```

